-- ============================================================
-- MonexUp Database Schema
-- PostgreSQL
-- Generated: 2026-04-03
-- Last updated: 2026-05-04 (feature 005-billing-migration to ProxyPay)
-- Prefix: monexup_
--
-- Feature 005 changes:
--   * monexup_networks: + proxypay_store_id, proxypay_client_id (lazy 1:1 store)
--   * monexup_invoice_fees:
--       - invoice_id is NULLABLE (legacy fee rows still link; new ProxyPay-driven
--         rows leave it NULL and use proxypay_invoice_id instead)
--       - + proxypay_invoice_id, reversed_at, paid_amount_cents_at_record, role
--       - UNIQUE (proxypay_invoice_id, user_id, role) WHERE proxypay_invoice_id
--         IS NOT NULL  -> idempotent upsert from completion-redirect + poller
--       - partial index on (network_id) WHERE reversed_at IS NULL  -> fast
--         per-network commission balance
-- monexup_invoices stays for now (Phase 5 / US3 cleanup is gated on staging
-- verification; once US3 ships, DROP it and the FK below).
-- ============================================================

-- Sequences
CREATE SEQUENCE IF NOT EXISTS monexup_network_id_seq;
CREATE SEQUENCE IF NOT EXISTS monexup_profile_id_seq;
CREATE SEQUENCE IF NOT EXISTS monexup_invoice_commission_id_seq;

-- ============================================================
-- Table: monexup_networks
-- ============================================================
CREATE TABLE monexup_networks (
    network_id BIGINT NOT NULL DEFAULT nextval('monexup_network_id_seq'::regclass),
    name VARCHAR(80) NOT NULL,
    email VARCHAR(180),
    commission DOUBLE PRECISION NOT NULL DEFAULT 0,
    withdrawal_min DOUBLE PRECISION NOT NULL DEFAULT 0,
    withdrawal_period INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    slug VARCHAR(100) NOT NULL,
    plan INTEGER NOT NULL DEFAULT 1,
    image VARCHAR(110),
    lofn_store_id BIGINT NULL,
    proxypay_store_id BIGINT NULL,
    proxypay_client_id VARCHAR(64) NULL,
    CONSTRAINT monexup_networks_pkey PRIMARY KEY (network_id)
);

CREATE INDEX ix_monexup_networks_lofn_store_id ON monexup_networks (lofn_store_id);
CREATE INDEX ix_monexup_networks_proxypay_store_id ON monexup_networks (proxypay_store_id);

-- ============================================================
-- Table: monexup_user_profiles
-- ============================================================
CREATE TABLE monexup_user_profiles (
    profile_id BIGINT NOT NULL DEFAULT nextval('monexup_profile_id_seq'::regclass),
    network_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    commission DOUBLE PRECISION NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT monexup_user_profiles_pkey PRIMARY KEY (profile_id),
    CONSTRAINT monexup_fk_user_profile_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id) ON DELETE SET NULL
);

CREATE INDEX idx_monexup_user_profiles_network_id ON monexup_user_profiles (network_id);

-- ============================================================
-- Table: monexup_user_networks
-- ============================================================
CREATE TABLE monexup_user_networks (
    user_id BIGINT NOT NULL,
    network_id BIGINT NOT NULL,
    profile_id BIGINT,
    referrer_id BIGINT,
    role INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT monexup_pk_user_network PRIMARY KEY (user_id, network_id),
    CONSTRAINT monexup_fk_user_network_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id) ON DELETE SET NULL,
    CONSTRAINT monexup_fk_user_network_profile FOREIGN KEY (profile_id)
        REFERENCES monexup_user_profiles (profile_id)
);

CREATE INDEX idx_monexup_user_networks_network_id ON monexup_user_networks (network_id);
CREATE INDEX idx_monexup_user_networks_profile_id ON monexup_user_networks (profile_id);

-- ============================================================
-- Table: monexup_orders
-- ============================================================
CREATE TABLE monexup_orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    seller_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    network_id BIGINT NOT NULL,
    CONSTRAINT monexup_orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT monexup_fk_order_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id) ON DELETE SET NULL
);

CREATE INDEX idx_monexup_orders_network_id ON monexup_orders (network_id);

-- ============================================================
-- Table: monexup_order_items
-- ============================================================
CREATE TABLE monexup_order_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT monexup_order_items_pkey PRIMARY KEY (item_id),
    CONSTRAINT monexup_fk_order_item FOREIGN KEY (order_id)
        REFERENCES monexup_orders (order_id) ON DELETE SET NULL
);

CREATE INDEX idx_monexup_order_items_order_id ON monexup_order_items (order_id);

-- ============================================================
-- Table: monexup_invoices
-- ============================================================
CREATE TABLE monexup_invoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    seller_id BIGINT,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    status INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT monexup_invoices_pkey PRIMARY KEY (invoice_id),
    CONSTRAINT monexup_fk_invoice_order FOREIGN KEY (order_id)
        REFERENCES monexup_orders (order_id) ON DELETE SET NULL
);

CREATE INDEX idx_monexup_invoices_order_id ON monexup_invoices (order_id);

-- ============================================================
-- Table: monexup_invoice_fees
-- ============================================================
CREATE TABLE monexup_invoice_fees (
    fee_id BIGINT NOT NULL DEFAULT nextval('monexup_invoice_commission_id_seq'::regclass),
    invoice_id BIGINT NULL,
    network_id BIGINT,
    user_id BIGINT,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    paid_at TIMESTAMP WITHOUT TIME ZONE,
    proxypay_invoice_id BIGINT NULL,
    reversed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    paid_amount_cents_at_record BIGINT NULL,
    role INTEGER NULL,
    CONSTRAINT monexup_pk_invoice_fee PRIMARY KEY (fee_id),
    CONSTRAINT monexup_fk_fee_invoice FOREIGN KEY (invoice_id)
        REFERENCES monexup_invoices (invoice_id) ON DELETE SET NULL,
    CONSTRAINT monexup_fk_fee_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id)
);

CREATE INDEX idx_monexup_invoice_fees_invoice_id ON monexup_invoice_fees (invoice_id);
CREATE INDEX ix_monexup_invoice_fees_proxypay_invoice_id ON monexup_invoice_fees (proxypay_invoice_id);
CREATE UNIQUE INDEX ix_monexup_invoice_fees_proxypay_invoice_user_role
    ON monexup_invoice_fees (proxypay_invoice_id, user_id, role)
    WHERE proxypay_invoice_id IS NOT NULL;
CREATE INDEX ix_monexup_invoice_fees_network_unreversed
    ON monexup_invoice_fees (network_id) WHERE reversed_at IS NULL;

-- ============================================================
-- Table: monexup_withdrawals
-- ============================================================
CREATE TABLE monexup_withdrawals (
    withdrawal_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    network_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    duedate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT monexup_withdrawals_pkey PRIMARY KEY (withdrawal_id),
    CONSTRAINT monexup_fk_withdrawal_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id) ON DELETE SET NULL
);

CREATE INDEX idx_monexup_withdrawals_network_id ON monexup_withdrawals (network_id);

-- ============================================================
-- Table: monexup_user_documents
-- ============================================================
CREATE TABLE monexup_user_documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    document_type INTEGER NOT NULL DEFAULT 0,
    base64 TEXT,
    CONSTRAINT monexup_user_documents_pkey PRIMARY KEY (document_id)
);

-- ============================================================
-- Table: monexup_product_links  (feature 004-lofn-products-migration)
-- Tracks ownership of a Lofn product on the MonexUp side.
-- Idempotency key: lofn_product_id (UNIQUE).
-- network_id FK ON DELETE CASCADE  -> ProductLinks die with their network.
-- user_id    FK NOT enforced at DB level (users live in NAuth schema).
-- ============================================================
CREATE TABLE monexup_product_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    lofn_product_id BIGINT NOT NULL,
    network_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT monexup_product_links_pkey PRIMARY KEY (id),
    CONSTRAINT monexup_fk_product_link_network FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_monexup_product_links_lofn_product_id
    ON monexup_product_links (lofn_product_id);
CREATE INDEX ix_monexup_product_links_network_user
    ON monexup_product_links (network_id, user_id);
CREATE INDEX ix_monexup_product_links_user
    ON monexup_product_links (user_id);
