-- =============================================================================
-- Migration (MINIMAL): feature 004-lofn-products-migration
-- Target:    PostgreSQL
--
-- USE THIS SCRIPT WHEN:
--   - The DB already has the `monexup_*` table-name prefix.
--   - The legacy `products` / `templates*` tables have already been dropped.
--   - You only need the NEW SCHEMA from feature 004 (column + table + indexes).
--
-- USE THE FULL SCRIPT (`lofn_products_migration.sql`) WHEN:
--   - The DB is still at state 20260223191527_InitialCreate (prefixless tables,
--     legacy products/templates still present).
--
-- This script is idempotent: every DDL statement uses `IF NOT EXISTS` /
-- guard checks so re-running is safe.
--
-- BEFORE RUNNING:
--   * Backup the database.
--   * Confirm there is no legacy product data left (audit T004 in research.md).
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS monexup_product_links;
--   DROP INDEX  IF EXISTS ix_monexup_networks_lofn_store_id;
--   ALTER TABLE monexup_networks DROP COLUMN IF EXISTS lofn_store_id;
-- =============================================================================

BEGIN;

-- 1. Add lofn_store_id column on monexup_networks (nullable; populated lazily
--    on first product CREATE for the network).
ALTER TABLE monexup_networks
    ADD COLUMN IF NOT EXISTS lofn_store_id bigint NULL;

-- 2. Index for joins / filters on lofn_store_id.
CREATE INDEX IF NOT EXISTS ix_monexup_networks_lofn_store_id
    ON monexup_networks (lofn_store_id);

-- 3. Create the new monexup_product_links table.
--    PK id, UNIQUE lofn_product_id (idempotency key), FK network_id ON DELETE CASCADE,
--    FK user_id (no DB-level FK; users live in NAuth schema).
CREATE TABLE IF NOT EXISTS monexup_product_links (
    id              integer GENERATED BY DEFAULT AS IDENTITY,
    lofn_product_id bigint NOT NULL,
    network_id      bigint NOT NULL,
    user_id         bigint NOT NULL,
    created_at      timestamp without time zone NOT NULL
                        DEFAULT ((now() at time zone 'utc')),
    CONSTRAINT monexup_product_links_pkey PRIMARY KEY (id),
    CONSTRAINT monexup_fk_product_link_network
        FOREIGN KEY (network_id)
        REFERENCES monexup_networks (network_id)
        ON DELETE CASCADE
);

-- 4. Indexes on monexup_product_links.
CREATE UNIQUE INDEX IF NOT EXISTS ix_monexup_product_links_lofn_product_id
    ON monexup_product_links (lofn_product_id);

CREATE INDEX IF NOT EXISTS ix_monexup_product_links_network_user
    ON monexup_product_links (network_id, user_id);

CREATE INDEX IF NOT EXISTS ix_monexup_product_links_user
    ON monexup_product_links (user_id);

-- 5. Record the migration in EF history so `dotnet ef database update` does
--    not try to re-apply the same DDL.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260504172626_LofnProductsMigration', '9.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260504172626_LofnProductsMigration'
);

COMMIT;

-- =============================================================================
-- Smoke checks (run after COMMIT):
--   SELECT column_name FROM information_schema.columns
--    WHERE table_name = 'monexup_networks' AND column_name = 'lofn_store_id';
--   SELECT to_regclass('monexup_product_links');
--   SELECT indexname FROM pg_indexes WHERE tablename = 'monexup_product_links';
--   SELECT * FROM "__EFMigrationsHistory" ORDER BY "MigrationId" DESC LIMIT 5;
-- =============================================================================
