// <auto-generated />
using System;
using DB.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Infra.Migrations
{
    [DbContext(typeof(MonexUpContext))]
    partial class MonexUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("monexup_invoice_commission_id_seq");

            modelBuilder.HasSequence("monexup_network_id_seq");

            modelBuilder.HasSequence("monexup_profile_id_seq");

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("InvoiceId")
                        .HasName("monexup_invoices_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("monexup_invoices", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.InvoiceFee", b =>
                {
                    b.Property<long>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fee_id")
                        .HasDefaultValueSql("nextval('monexup_invoice_commission_id_seq'::regclass)");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long?>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("FeeId")
                        .HasName("monexup_pk_invoice_fee");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("NetworkId");

                    b.ToTable("monexup_invoice_fees", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Network", b =>
                {
                    b.Property<long>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("network_id")
                        .HasDefaultValueSql("nextval('monexup_network_id_seq'::regclass)");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision")
                        .HasColumnName("commission");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasMaxLength(110)
                        .HasColumnType("character varying(110)")
                        .HasColumnName("image");

                    b.Property<long?>("LofnStoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("lofn_store_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Plan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<double>("WithdrawalMin")
                        .HasColumnType("double precision")
                        .HasColumnName("withdrawal_min");

                    b.Property<int>("WithdrawalPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("withdrawal_period");

                    b.HasKey("NetworkId")
                        .HasName("monexup_networks_pkey");

                    b.HasIndex("LofnStoreId")
                        .HasDatabaseName("ix_monexup_networks_lofn_store_id");

                    b.ToTable("monexup_networks", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("monexup_orders_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("monexup_orders", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.OrderItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("ItemId")
                        .HasName("monexup_order_items_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("monexup_order_items", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.ProductLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<long>("LofnProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("lofn_product_id");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("monexup_product_links_pkey");

                    b.HasIndex("LofnProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_monexup_product_links_lofn_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_monexup_product_links_user");

                    b.HasIndex("NetworkId", "UserId")
                        .HasDatabaseName("ix_monexup_product_links_network_user");

                    b.ToTable("monexup_product_links", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("Base64")
                        .HasColumnType("text")
                        .HasColumnName("base64");

                    b.Property<int>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("document_type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("DocumentId")
                        .HasName("monexup_user_documents_pkey");

                    b.ToTable("monexup_user_documents", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserNetwork", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("UserId", "NetworkId")
                        .HasName("monexup_pk_user_network");

                    b.HasIndex("NetworkId");

                    b.HasIndex("ProfileId");

                    b.ToTable("monexup_user_networks", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("nextval('monexup_profile_id_seq'::regclass)");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision")
                        .HasColumnName("commission");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.HasKey("ProfileId")
                        .HasName("monexup_user_profiles_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("monexup_user_profiles", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Withdrawal", b =>
                {
                    b.Property<long>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("withdrawal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WithdrawalId"));

                    b.Property<DateTime>("Duedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("duedate");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("WithdrawalId")
                        .HasName("monexup_withdrawals_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("monexup_withdrawals", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.HasOne("DB.Infra.Context.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_invoice_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DB.Infra.Context.InvoiceFee", b =>
                {
                    b.HasOne("DB.Infra.Context.Invoice", "Invoice")
                        .WithMany("InvoiceFees")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_fee_invoice");

                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("InvoiceFees")
                        .HasForeignKey("NetworkId")
                        .HasConstraintName("monexup_fk_fee_network");

                    b.Navigation("Invoice");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Orders")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_order_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.OrderItem", b =>
                {
                    b.HasOne("DB.Infra.Context.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_order_item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DB.Infra.Context.ProductLink", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("ProductLinks")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("monexup_fk_product_link_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.UserNetwork", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("UserNetworks")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_user_network_network");

                    b.HasOne("DB.Infra.Context.UserProfile", "Profile")
                        .WithMany("UserNetworks")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("monexup_fk_user_network_profile");

                    b.Navigation("Network");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("UserProfiles")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_user_profile_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Withdrawal", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Withdrawals")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("monexup_fk_withdrawal_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.Navigation("InvoiceFees");
                });

            modelBuilder.Entity("DB.Infra.Context.Network", b =>
                {
                    b.Navigation("InvoiceFees");

                    b.Navigation("Orders");

                    b.Navigation("ProductLinks");

                    b.Navigation("UserNetworks");

                    b.Navigation("UserProfiles");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.Navigation("UserNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
