// <auto-generated />
using System;
using DB.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Infra.Migrations
{
    [DbContext(typeof(MonexUpContext))]
    partial class MonexUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("invoice_commission_commission_id_seq");

            modelBuilder.HasSequence("network_id_seq");

            modelBuilder.HasSequence("profile_id_seq");

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("StripeId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("InvoiceId")
                        .HasName("invoices_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.InvoiceFee", b =>
                {
                    b.Property<long>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fee_id")
                        .HasDefaultValueSql("nextval('invoice_commission_commission_id_seq'::regclass)");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<long?>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("FeeId")
                        .HasName("pk_invoice_fee");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("NetworkId");

                    b.ToTable("invoice_fees", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Network", b =>
                {
                    b.Property<long>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("network_id")
                        .HasDefaultValueSql("nextval('network_id_seq'::regclass)");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision")
                        .HasColumnName("commission");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasMaxLength(110)
                        .HasColumnType("character varying(110)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Plan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<double>("WithdrawalMin")
                        .HasColumnType("double precision")
                        .HasColumnName("withdrawal_min");

                    b.Property<int>("WithdrawalPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("withdrawal_period");

                    b.HasKey("NetworkId")
                        .HasName("networks_pkey");

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("StripeId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.OrderItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("ItemId")
                        .HasName("order_items_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("frequency");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("image");

                    b.Property<int>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_price_id");

                    b.Property<string>("StripeProductId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_product_id");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Template", b =>
                {
                    b.Property<long>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TemplateId"));

                    b.Property<string>("Css")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("css");

                    b.Property<long?>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TemplateId")
                        .HasName("templates_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.TemplatePage", b =>
                {
                    b.Property<long>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PageId"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("character varying(170)")
                        .HasColumnName("title");

                    b.HasKey("PageId")
                        .HasName("template_pages_pkey");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_pages", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.TemplatePart", b =>
                {
                    b.Property<long>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PartId"));

                    b.Property<double>("Order")
                        .HasColumnType("double precision")
                        .HasColumnName("order");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<string>("PartKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("part_key");

                    b.HasKey("PartId")
                        .HasName("template_parts_pkey");

                    b.HasIndex("PageId");

                    b.ToTable("template_parts", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.TemplateVar", b =>
                {
                    b.Property<long>("VarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("var_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VarId"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<int>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("language");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("VarId")
                        .HasName("template_vars_pkey");

                    b.HasIndex("PageId");

                    b.ToTable("template_vars", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("Base64")
                        .HasColumnType("text")
                        .HasColumnName("base64");

                    b.Property<int>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("document_type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("DocumentId")
                        .HasName("user_documents_pkey");

                    b.ToTable("user_documents", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserNetwork", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.Property<long?>("ReferrerId")
                        .HasColumnType("bigint")
                        .HasColumnName("referrer_id");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("UserId", "NetworkId")
                        .HasName("pk_user_network");

                    b.HasIndex("NetworkId");

                    b.HasIndex("ProfileId");

                    b.ToTable("user_networks", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("nextval('profile_id_seq'::regclass)");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision")
                        .HasColumnName("commission");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.HasKey("ProfileId")
                        .HasName("user_profiles_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Withdrawal", b =>
                {
                    b.Property<long>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("withdrawal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WithdrawalId"));

                    b.Property<DateTime>("Duedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("duedate");

                    b.Property<long>("NetworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("network_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("WithdrawalId")
                        .HasName("withdrawals_pkey");

                    b.HasIndex("NetworkId");

                    b.ToTable("withdrawals", (string)null);
                });

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.HasOne("DB.Infra.Context.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_invoice_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DB.Infra.Context.InvoiceFee", b =>
                {
                    b.HasOne("DB.Infra.Context.Invoice", "Invoice")
                        .WithMany("InvoiceFees")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("fk_fee_invoice");

                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("InvoiceFees")
                        .HasForeignKey("NetworkId")
                        .HasConstraintName("fk_fee_network");

                    b.Navigation("Invoice");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Orders")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_order_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.OrderItem", b =>
                {
                    b.HasOne("DB.Infra.Context.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_order_item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DB.Infra.Context.Product", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Products")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_network_product");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Template", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Templates")
                        .HasForeignKey("NetworkId")
                        .HasConstraintName("fk_template_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.TemplatePage", b =>
                {
                    b.HasOne("DB.Infra.Context.Template", "Template")
                        .WithMany("TemplatePages")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("fk_template_page");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DB.Infra.Context.TemplatePart", b =>
                {
                    b.HasOne("DB.Infra.Context.TemplatePage", "Page")
                        .WithMany("TemplateParts")
                        .HasForeignKey("PageId")
                        .IsRequired()
                        .HasConstraintName("fk_template_part_page");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DB.Infra.Context.TemplateVar", b =>
                {
                    b.HasOne("DB.Infra.Context.TemplatePage", "Page")
                        .WithMany("TemplateVars")
                        .HasForeignKey("PageId")
                        .IsRequired()
                        .HasConstraintName("fk_template_var_page");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DB.Infra.Context.UserNetwork", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("UserNetworks")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_user_network_network");

                    b.HasOne("DB.Infra.Context.UserProfile", "Profile")
                        .WithMany("UserNetworks")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("fk_user_network_profile");

                    b.Navigation("Network");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("UserProfiles")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Withdrawal", b =>
                {
                    b.HasOne("DB.Infra.Context.Network", "Network")
                        .WithMany("Withdrawals")
                        .HasForeignKey("NetworkId")
                        .IsRequired()
                        .HasConstraintName("fk_withdrawal_network");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("DB.Infra.Context.Invoice", b =>
                {
                    b.Navigation("InvoiceFees");
                });

            modelBuilder.Entity("DB.Infra.Context.Network", b =>
                {
                    b.Navigation("InvoiceFees");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Templates");

                    b.Navigation("UserNetworks");

                    b.Navigation("UserProfiles");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("DB.Infra.Context.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DB.Infra.Context.Template", b =>
                {
                    b.Navigation("TemplatePages");
                });

            modelBuilder.Entity("DB.Infra.Context.TemplatePage", b =>
                {
                    b.Navigation("TemplateParts");

                    b.Navigation("TemplateVars");
                });

            modelBuilder.Entity("DB.Infra.Context.UserProfile", b =>
                {
                    b.Navigation("UserNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
